name: build_master

on:
    pull_request:

jobs:
  build:
    name: Builds ion-java with ${{ matrix.java_version }}
    strategy:
      matrix:
        java_version: [8, 9, 10, 11]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout change
      uses: actions/checkout@v1

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml
