# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: PR Content Check

on:
  workflow_call:
    outputs:
      result:
        description: "The result of PR content check"
        value: ${{ jobs.check-PR-content.outputs.output1 }}

jobs:
  check-PR-content:
    name: Check PR Content

    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.check-content.outputs.result }}

    steps:
      - name: Checkout the incoming pull request
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          path: ion-java-new

      - name: Check the content of the last commit
        id: check-content
        run: |
          cd ion-java-new
          if [[ $(git log -1 --name-only) == *"src/"* ]]; then echo "result=pass" >> $GITHUB_OUTPUT; else echo "result=fail" >> $GITHUB_OUTPUT; fi
