# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: PR Content Check

on: [pull_request]

jobs:
  check-PR-content:
    name: Check PR Content

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the incoming pull request
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          path: ion-java-new

      - name: Check the content of the last commit
        id: check-content
        run: |
          cd ion-java-new
          if [[ $(git log -1 --name-only) == *"src/"* ]]; then echo "result=pass"; else exit 1; fi